version: '2.0'
services:
  db:
    image: mariadb:10.5
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=db_dev  # [IMPORTANT] Change the mySQL root password
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /mnt/data/portadisk/software/seafile/mysql:/var/lib/mysql  # [IMPORTANT] Change the data directory to your data disk
    networks:
      - seafile-net

  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    entrypoint: memcached -m 156 # Bump this up to 256 if desired, as the Pi Zero is a low memory device we can't give half of the RAM to memcached
    networks:
      - seafile-net
          
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    ports:
      - "1337:80" # Don't change this
    volumes:
      - /mnt/data/portadisk/software/seafile/data:/shared   # [IMPORTANT] Change the data directory to your data disk
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=db_dev  # [IMPORTANT] set this to your mySQL password.
      - TIME_ZONE=Europe/Berlin  # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=me@example.com # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=asecret     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME=docs.seafile.com # Specifies your host name if https is enabled.
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net

networks:
  seafile-net: